### ISSUE TITLE
can not create trigger 

### ISSUE THREAD

**Issue by zhy989** [lzbj/openwhisk-data-processing-message-hub-watson#1]
wsk trigger create kafka-trigger \
  --feed /_/Bluemix_${KAFKA_INSTANCE_NAME}_Credentials-1/messageHubFeed \
  --param isJSONData true \
  --param topic ${SRC_TOPIC}

- error: Unable to create trigger 'kafka-trigger': Unable to invoke trigger 'kafka-trigger' feed action '/_/Bluemix_kafka-broker_Credentials-1/messageHubFeed'; feed is not configured: Unable to invoke action 'Bluemix_kafka-broker_Credentials-1/messageHubFeed': The requested resource does not exist. (code 11644542)

where can I get the feed package?

**Comment by lzbj** [comment]
@zhy989 , thanks for your interestes.

Please reference README.md https://github.com/lzbj/openwhisk-data-processing-message-hub-watson/blob/master/README.md.

I suggest you first use the shell scripts to automatically deploy, and then go with you manual steps, if you have issues, please take a look into the deploy and undeploy shell scripts,  the manual steps just as the same as shell scripts.

**Comment by zhy989** [comment]
@lzbj thanks
I run the deploy shell script, also can not create trigger successfully. I get the log as below:

- Activation: messageHubFeed (ee4823ea93a24cf4bf6166f04c2a6cd4)
[
    "2017-07-21T07:21:48.035654133Z stdout: Error creating trigger: {",
    "2017-07-21T07:21:48.035754712Z stdout: \"name\": \"StatusCodeError\",",
    "2017-07-21T07:21:48.035763356Z stdout: \"statusCode\": 500,",
    "2017-07-21T07:21:48.035776013Z stdout: \"message\": \"500 - \\\"Topic does not exist. You must create the topic first: in-topic\\\"\",",
    "2017-07-21T07:21:48.035786856Z stdout: \"error\": \"Topic does not exist. You must create the topic first: in-topic\",",

I create the Message Hub service kafka-broker from Bluemix, but  I do not know how to create the in-topic and out-topic.

**Comment by lzbj** [comment]
you could reference IBM message hub documents on Bluemix

**Comment by zhy989** [comment]
@lzbj  thanks 

I can create trigger successfully
